"""
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.



Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
"""
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        a=0
        b=0
        for i in t:
            a+=ord(i)
        for i in s:
            b+=ord(i)
        return chr(abs(b-a))
obj=Solution()
res=obj.findTheDifference("abcd","abcde")
print(res)
